sudo: required
services: -docker

before_install:
  - docker build -t gustavolee/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gustavolee/react-test npm test -- --coverage

after_success:
  - docker build -t gustavolee/multi-client ./client
  - docker build -t gustavolee/multi-nginx ./nginx
  - docker build -t gustavolee/multi-server ./server
  - docker build -t gustavolee/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to Docker Hub
  - docker push gustavolee/multi-client
  - docker push gustavolee/multi-nginx
  - docker push gustavolee/multi-server
  - docker push gustavolee/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: multi-docker
  env: multi-docker-env
  bucket_name: elasticbeanstalk-ap-northeast-2-291539272605
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
